<?php include_once( 'nav.inc' ); ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="description" content="Emily Brower Auchard, Copywriter">
    <title>Emily Brower Auchard, Copywriter - Advertising</title>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.6.0/build/fonts/fonts.css">
    <link rel="stylesheet" type="text/css" href="site.css">
</head>
<body>
    <div id="frame">
        <div id="leftCol">
            <?php include_once( 'header.inc' ); ?>
            <div id="nav"><?php buildNav( $pageId ); ?></div>
        </div>
